[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
providers = ["java"]

[variables]
NIXPACKS_JDK_VERSION = "17"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/api/academic-years"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"



